- Makefile
- app/app.go
- app/e2e_include_upgrades.go
- app/upgrades/vanilla/upgrades.go
- contrib/images/Makefile
- contrib/images/babylond/Dockerfile
- contrib/images/e2e-initialization/init.Dockerfile
- go.mod
- test/e2e/btc_staking_e2e_test.go
- test/e2e/configurer/base.go
- test/e2e/configurer/chain/chain.go
- test/e2e/configurer/chain/commands.go
- test/e2e/configurer/chain/node.go
- test/e2e/configurer/chain/queries.go
- test/e2e/configurer/config/constants.go
- test/e2e/configurer/factory.go
- test/e2e/configurer/setup.go
- test/e2e/configurer/upgrade.go
- test/e2e/containers/config.go
- test/e2e/containers/containers.go
- test/e2e/e2e_test.go
- test/e2e/ibc_transfer_e2e_test.go
- test/e2e/initialization/config.go
- test/e2e/initialization/export.go
- test/e2e/initialization/node.go
- test/e2e/software_upgrade_e2e_test.go
- test/e2e/upgrades/vanilla.json
- wasmbinding/testdata/README.md
- Test e2e upgrade test with current `dev` branch - 5f8af8ced17d24f3f0c6172293cd37fb3d055807
Applied from PRs https://github.com/babylonchain/babylon/pull/730 and https://github.com/babylonchain/babylon/pull/727
> chore: e2e upgrade

- types/retry/retry.go
- types/retry/retry_test.go
We have regression in our retry library. 
Due to this regression all errors returned by provided functions are shadowed by error from - `jitter, err := randDuration(int64(sleep))`
This makes vigilante tests fail - https://github.com/babylonlabs-io/vigilante/actions/runs/10281209916/job/28451257642?pr=5
> Fix shadowing in retry library 

- CONTRIBUTING.md
- RELEASE_PROCESS.md
First step of switching to trunk based development process. 
Docs are highly influenced by:
- https://github.com/cosmos/gaia/blob/main/RELEASE_PROCESS.md
- https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md
But adapted to Babylon situation i.e we do not have yet any testnet, mainnet, nor any stable version released. We also do not have yet:
- changelog process
- release note process
- we do not use `goreleaser` for building binaries on different platforms
All this things should be added in next steps and documents should be updated to reflect usage of those practices.
After merging this pr, we should merge `dev` to `main` and delete the `dev` branch, and follow the process described in those documents.
Adding whole team as reviewers, so that we are all on the same page.
> Add release process and contributing docs

- contrib/images/Makefile
- contrib/images/e2e-initialization/init.Dockerfile
Add version argument for initialization docker for e2e tests to run with arguments and types expected by the pre-upgraded state
> chore: add version argument for e2e-initialization

- app/upgrades/signetlaunch/btcstaking_params.go
- app/upgrades/signetlaunch/btcstaking_params_test.go
- app/upgrades/signetlaunch/upgrades.go
- app/upgrades/signetlaunch/upgrades_test.go
- test/e2e/software_upgrade_e2e_signet_launch_test.go
- x/btcstaking/keeper/params.go
- Add parameters upgrade from TGE chain
- Add e2e test
Depends on fixing: https://github.com/babylonlabs-io/babylon/pull/46, so that `init-chain` docker image can be build from TGE version i.e before upgrade
> feat: btcstaking parameters upgrade

- app/upgrades/signetlaunch/btcstaking_params.go
- app/upgrades/signetlaunch/btcstaking_params_test.go
- app/upgrades/signetlaunch/upgrades.go
- app/upgrades/signetlaunch/upgrades_test.go
- btcstaking/staking.go
- btcstaking/staking_test.go
- cmd/babylond/cmd/flags.go
- cmd/babylond/cmd/genesis.go
- cmd/babylond/cmd/genhelpers/set_btc_delegations_test.go
- cmd/babylond/cmd/testnet.go
- proto/babylon/btcstaking/v1/params.proto
- test/e2e/btc_staking_e2e_test.go
- test/e2e/software_upgrade_e2e_signet_launch_test.go
- testutil/datagen/btcstaking.go
- x/btcstaking/keeper/grpc_query_test.go
- x/btcstaking/keeper/keeper_test.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/keeper/params.go
- x/btcstaking/keeper/params_test.go
- x/btcstaking/keeper/query_params_test.go
- x/btcstaking/types/btc_delegation_test.go
- x/btcstaking/types/btc_slashing_tx_test.go
- x/btcstaking/types/btc_undelegation_test.go
- x/btcstaking/types/btcstaking.go
- x/btcstaking/types/genesis_test.go
- x/btcstaking/types/params.go
- x/btcstaking/types/params.pb.go
- x/btcstaking/types/validate_parsed_message.go
- x/btcstaking/types/validate_parsed_message_test.go
ref: https://github.com/babylonlabs-io/pm/issues/19
Implement ADR-23 to make babylon chain parameters compatible with [phase-1](https://github.com/babylonlabs-io/pm/blob/main/adr/adr-023-update-btcstaking-params.md):
> feat: ADR-23 Update staking parameters structure

- docs/architecture.md
- docs/run-node.md
- docs/staking-script.md
- docs/transaction-impl-spec.md
Corrected typos and grammatical mistakes in multiple documentation files. These changes are intended to enhance the overall quality and readability of the documentation, making it easier for users and contributors to understand and follow.
> fix: grammatical errors in documentation

- cmd/babylond/cmd/custom_babylon_config.go
- cmd/babylond/cmd/genesis.go
- cmd/babylond/cmd/root.go
- cmd/babylond/cmd/testnet.go
- contrib/images/babylond/Dockerfile
- test/e2e/initialization/node.go
- Add default gen state to `ibc` module
- Add `jq` to dockerfile, needed to local deployments
- Specify min gas prices as default `1ubbn` in a single place
> fix: testnet command minor issues

- CHANGELOG.md
- x/checkpointing/keeper/grpc_query_bls_test.go
- x/checkpointing/keeper/val_bls_set_test.go
- x/epoching/keeper/epoch_val_set_test.go
- x/epoching/keeper/epochs.go
When we initialize epoch, we should also initialize epoch 1. Otherwise, epoch 0 will be accessed
> fix: Epoch initial height

- CHANGELOG.md
After this is merged into `release/v0.10.x`, a new tag will be released
> chore: release v0.10.1

- test/e2e/configurer/chain/chain.go
- test/e2e/ibc_transfer_e2e_test.go
Improve IBC coin transfer tests.
> f/Better IBC transfer tests

- CHANGELOG.md
- x/btcstaking/types/btc_delegation.go
> fix: removed btc status unbonding from error return string

- CHANGELOG.md
- x/btcstaking/keeper/btc_delegations.go
- x/btcstaking/keeper/keeper_test.go
- x/btcstaking/keeper/power_dist_change_test.go
Pr: https://github.com/babylonlabs-io/babylon/pull/130 allowed for accepting covenant signatures after quorum is reached.
This change introduces regression i.e covenant signatures accepted after quorum is reached also generated voting power events, this could lead to weird results in processing voting power events.
This pr fixes that by making sure that events of any kind are generated only if this is first time quorum is reached.
> fix handling covent message when quorum is already reached

- .github/workflows/backport.yml
- RELEASE_PROCESS.md
Part of https://github.com/babylonlabs-io/babylon/issues/110
This PR introduces the backport Github action. One can label a hotfix PR to `main` with `backport release/0.Y.x`, and this GH action will open a backport PR automatically.
> chore: backport github action

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/publish.yml
Resolves #110 
This PR adds Github actions for changelog reminder and goreleaser. Also this PR bumps the dependency of babylonlabs-io/.github to v0.7.0
TODOs before merging:
> ci: add Github actions for changelog reminder and goreleaser

- CHANGELOG.md
- x/btcstaking/client/cli/tx.go
We're accessing arg at index 1, but should be at 0
> fix(btcstaking/client): edit fp arg

- .github/workflows/changelog-reminder.yml
- .github/workflows/ci.yml
- .gitignore
- .goreleaser.yml
- CHANGELOG.md
- Makefile
- RELEASE_PROCESS.md
This PR 
- sets up Go releaser for Babylon. Currently it only supports linux amd64. Other targets will be supported in the future. To test locally, run `make release-snapshot`
- moves changelog reminder out from the CI flow
> ci: add goreleaser setup and move out changelog reminder

- CHANGELOG.md
- x/btcstaking/types/btcstaking.go
- x/btcstaking/types/btcstaking_test.go
Non-determinism is caused due to not considering cases where both two items are jailed or non-timestamped, and when voting power is equal. This PR addressed this by determining the order in those cases by the increasing order of btc pk hex.
> fix: Non-determinism in sorting finality providers in the voting power table

- CHANGELOG.md
- x/btcstaking/types/btcstaking.go
- x/btcstaking/types/btcstaking_test.go
This is a manual backport as the automatic process failed due to conflicts in changelog
> backport: Fix non-determinism in sorting finality providers in the voting power table (#180)

- CHANGELOG.md
- btcstaking/staking.go
- btcstaking/staking_test.go
- x/btcstaking/types/create_delegation_parser.go
- x/btcstaking/types/validate_parsed_message.go
Add:
- new `btcstaking` library function to validate whether transactions are standard based on https://github.com/btcsuite/btcd/blob/ee68dc66a835bf2c9333f3d7b33791841f561c84/mempool/policy.go#L285
- use those function to validate unbonding / slashing transactions
- test suite to test new functions
> Properly validate whether tranactions are standard

- CHANGELOG.md
- btcstaking/staking.go
- btcstaking/staking_test.go
- x/btcstaking/types/create_delegation_parser.go
- x/btcstaking/types/validate_parsed_message.go
Add:
- new `btcstaking` library function to validate whether transactions are standard based on
https://github.com/btcsuite/btcd/blob/ee68dc66a835bf2c9333f3d7b33791841f561c84/mempool/policy.go#L285
- use those function to validate unbonding / slashing transactions
- test suite to test new functions
> Properly validate whether tranactions are standard (#185)

- CHANGELOG.md
- x/finality/keeper/msg_server.go
- x/finality/keeper/msg_server_test.go
- x/finality/types/msg.go
If not would receive finality vote with `nil` Proof, it would panic. 
Pr:
- fixes that
- add test case 
Fixes: https://github.com/babylonlabs-io/babylon/issues/174
> Do not panic on nil proof when handling votes

- CHANGELOG.md
- x/btcstaking/types/btc_delegation.go
- x/btcstaking/types/btc_delegation_test.go
- x/btcstaking/types/btc_slashing_tx.go
- x/btcstaking/types/btc_slashing_tx_test.go
- x/btcstaking/types/btc_undelegation_test.go
Also adapts all tests to ensure the witness construction works even if all covenant members provide signatures.
> fix: fixing witness construction of slashing tx

- CHANGELOG.md
- x/btcstaking/types/validate_parsed_message_test.go
Closes #251. The flunky is caused due to the fact that the test uses `uint16` type for the `stakingTimeBlocks` which is generated in a range of min and max staking time (0, 100000). However, the max value of `uint16` is 65535. This PR changes the value of max staking time to 10000 to avoid overflow.
> chore: Fix flunky TestValidateParsedMessageAgainstTheParams

- CHANGELOG.md
- x/checkpointing/keeper/keeper.go
Fix error handling in checkpointing module:
- the line `err = types.ErrInvalidCkptStatus.Wrapf("the status of the checkpoint should be %s", from.String())` was just allocating error and not doing anything with it
- error from `ckptWithMeta, err := k.GetRawCheckpoint(ctx, epoch)` was just getting swallowed
> fix error handling in checkpointing module

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- CHANGELOG.md
Make github action actually make a go release package and added into release note to be able download by all the audience. Remove libwasmvm for github action using whatever is defined in the go mod file library.
> feat: fix go releaser and hook by github action

- CHANGELOG.md
- client/query/finality.go
Root cause of https://github.com/babylonlabs-io/finality-provider/issues/121. If response is nil due to error, will cause panic
> fix(client): Panic due to possible nil params response

- CHANGELOG.md
- test/e2e/btc_staking_e2e_test.go
- test/e2e/btc_staking_pre_approval_e2e_test.go
- testutil/btcstaking-helper/keeper.go
- x/btccheckpoint/keeper/msg_server.go
- x/btccheckpoint/keeper/msg_server_test.go
- x/btcstaking/keeper/btc_delegations.go
- x/btcstaking/keeper/genesis_test.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/keeper/params.go
- x/btcstaking/types/btcstaking.go
- x/btcstaking/types/params.go
- x/btcstaking/types/validate_parsed_message.go
- x/btcstaking/types/validate_parsed_message_test.go
- x/finality/keeper/power_dist_change_test.go
Closes #263. In particular,
- ensure `checkpointFinalizationTimeout` can never be changed in the update params handler of the btccheckpoint module
- ensure `minUnbondingTime` can not be set to a value less than or equal to `checkpointFinalizationTimeout` in the update params handler of the btcstaking module
- allows `unbondingTime` of a delegation to be set to a value equals to `minUnbondingTime`
> chore: Allow unbonding time to be min unbonding value

- CHANGELOG.md
- testutil/btcstaking-helper/keeper.go
- testutil/datagen/btc_transaction.go
- x/btcstaking/keeper/btc_delegations.go
- x/btcstaking/keeper/genesis_test.go
- x/btcstaking/keeper/inclusion_proof.go
- x/btcstaking/keeper/inclusion_proof_test.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/types/params.go
The bug is caused due to setting `params.MinStakingTime` to the btcstaking module's keeper method `VerifyInclusionProofAndGetHeight` other than `params.MinUnbondingTime`. In the fix, we remove `minUnbondingTime` from the parameter list of `VerifyInclusionProofAndGetHeight` as it should retrieve the parameter within the method.
This PR also added comprehensive tests for `VerifyInclusionProofAndGetHeight`
> hotfix: Invalid minUnbondingTime for verifying inclusion proof

- CHANGELOG.md
- testutil/btcstaking-helper/keeper.go
- testutil/datagen/btc_transaction.go
- x/btcstaking/keeper/btc_delegations.go
- x/btcstaking/keeper/genesis_test.go
- x/btcstaking/keeper/inclusion_proof.go
- x/btcstaking/keeper/inclusion_proof_test.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/types/params.go
The bug is caused due to setting `params.MinStakingTime` to the btcstaking module's keeper method `VerifyInclusionProofAndGetHeight` other than `params.MinUnbondingTime`. In the fix, we remove `minUnbondingTime` from the parameter list of
`VerifyInclusionProofAndGetHeight` as it should retrieve the parameter within the method.
This PR also added comprehensive tests for
`VerifyInclusionProofAndGetHeight`
> backport: Fix invalid minUnbondingTime for verifying inclusion proof (#289)

- CHANGELOG.md
- btcstaking/staking.go
- btcstaking/staking_test.go
- Enforces that unbonding tx always have version `2`
> Enforce that unbonding tx always has version 2

- CHANGELOG.md
- btcstaking/staking.go
- btcstaking/staking_test.go
- Enforces that unbonding tx always have version `2`
> Backport v0.17.x: Enforce that unbonding tx always has version 2 (#311)

- CHANGELOG.md
- testutil/btcstaking-helper/keeper.go
- x/btcstaking/keeper/grpc_query.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/types/btc_delegation.go
- x/btcstaking/types/btc_delegation_test.go
With recent changes:
- enforcing that `min_unbonding_time` is always larger than `checkpoint_finalization_timeout`
- changing `min_unbonding_time` to exact `unbonding_time`
`GetStatus` can now rely on `UnbondingTime` in delegation instead of `checkpoint_finalization_timeout`
> fix getStatus call on BTCDelegation

- CHANGELOG.md
- x/finality/keeper/msg_server.go
- x/finality/types/metrics.go
Closes #259. Using gauge is not easy to fix the issue as we don't know the number of fps being jailed. Therefore, this PR fixed the issue by adding a separate counter for unjailed fps.
> fix: Decrementing jailed fp counter

- go.mod
- go.sum
- test/e2e/app_replay_e2e_test.go
- test/replay/app_replay_e2e_test.go
Adds initial scaffold for tests which enable full execution of the block by comet-bft utilities:
- `BlockExecutor`
Those are test can be used in various scenarios:
- e2e application test  asserting  that after certain ordered operations, we reached expected state
- deterministic execution tests i.e execute some random operations and replay them and check that app hash matches
- early block execution tests (if we introduce other backends than memdb)
> Add scaffold to test replaying the block of the app

- CHANGELOG.md
- cmd/babylond/cmd/debug.go
- cmd/babylond/cmd/root.go
- Helps to convert keys from pub key 
```shell
babylond debug pubkey-raw "A2h06lj/GAPW1RvJE3HU9yetMGCR9K7a+tcwwTYT8t7z"
Parsed key as secp256k1
Address: 3565AEBC1D0CF089A4C2B04500EFE5007701604E
JSON (base64): {"type":"tendermint/PubKeySecp256k1","value":"A2h06lj/GAPW1RvJE3HU9yetMGCR9K7a+tcwwTYT8t7z"}
Bech32 Acc: bbnpub1addwnpepqd58f6jcluvq84k4r0y3xuw57un66vrqj862akh66ucvzdsn7t00x5n57a8
Bech32 Validator Operator: bbnvaloperpub1addwnpepqd58f6jcluvq84k4r0y3xuw57un66vrqj862akh66ucvzdsn7t00x4p4spq
Bech32 Validator Consensus: 
BIP340 Hex: 036874ea58ff1803d6d51bc91371d4f727ad306091f4aedafad730c13613f2def3
```
> chore: add print bip 340 to debug pubkey-raw

- CHANGELOG.md
- testutil/btcstaking-helper/keeper.go
- x/finality/keeper/liveness.go
- x/finality/keeper/liveness_test.go
- x/finality/keeper/power_table.go
The voting power table is a map which causes random order of processing jailing events. If more than one fps jailed at one block, non-determinism could happen. The PR fixed this by introducing ordered voting power table which retains the order from interating the `votingPowerBbnBlockHeightStore`
> [backport] fix: non-determinism while jailing

- test/replay/btcstaking_test.go
- test/replay/driver.go
- test/replay/finality_test.go
- testutil/datagen/btc_blockchain.go
- Add fuzzing test case showing our jailing is non-deterministic now
> andomnes commit replay test

- CHANGELOG.md
- app/app.go
- app/app_test.go
- app/encoding.go
- app/keepers/keepers.go
- app/keepers/utils.go
- app/params/addr.go
- app/signer/private.go
- app/test_helpers.go
- app/upgrades/v1/upgrades_test.go
- cmd/babylond/cmd/genhelpers/bls_add_test.go
- cmd/babylond/cmd/genhelpers/bls_create_test.go
- cmd/babylond/cmd/root.go
- cmd/babylond/cmd/testnet_test.go
- cmd/babylond/cmd/validate_genesis_test.go
- test/replay/driver.go
- testutil/datagen/genesiskey.go
- testutil/helper/helper.go
- testutil/keeper/btccheckpoint.go
- testutil/keeper/btclightclient.go
- testutil/keeper/btcstaking.go
- testutil/keeper/epoching.go
- testutil/keeper/finality.go
- testutil/keeper/incentive.go
- testutil/signer/private.go
- x/btccheckpoint/keeper/msg_server_test.go
- x/btcstaking/keeper/msg_server_test.go
- x/mint/module_test.go
- Move `PrivateSigner` to specific package
- Created vars for constant used Mod accounts in appparams
> chore: refactory

- .github/workflows/ci.yml
- Makefile
- proto/babylon/btcstaking/v1/events.proto
- proto/babylon/btcstkconsumer/v1/btcstkconsumer.proto
- proto/babylon/checkpointing/v1/query.proto
- proto/babylon/finality/v1/tx.proto
- proto/babylon/incentive/query.proto
- proto/babylon/mint/v1/query.proto
This PR removes unused dependencies in `.proto` files, addressing the protobuf generation issue outlined in [babylon-contract/issues/101](https://github.com/babylonlabs-io/babylon-contract/issues/101).
```
make proto-lint
```
> fix: remove unused deps in `.proto` files

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- proto/babylon/btcstaking/v1/events.proto
- proto/babylon/checkpointing/v1/query.proto
- proto/babylon/incentive/query.proto
- proto/babylon/mint/v1/query.proto
This PR backports this update https://github.com/babylonlabs-io/babylon/pull/355 to the `main` branch.
```
make proto-lint
```
> [backport] remove unused deps in `.proto` files

- app/upgrades/v1/README.md
Hello,
I have two suggestions for this document:
First, there is a typo in "devenet data". It should be "devnet data", Second, a grammatical error, "all the BTC block headers that has passed since babylon started"; "has" should be replaced as "have".
Thanks.
> Typo suggestions for Update README.md

- CHANGELOG.md
- test/e2e/btc_rewards_distribution_e2e_test.go
- testutil/btcstaking-helper/keeper.go
- testutil/incentives-helper/keeper.go
- x/btcstaking/keeper/bench_test.go
- x/btcstaking/keeper/msg_server_test.go
- x/finality/keeper/liveness_test.go
- x/finality/keeper/power_dist_change.go
- x/finality/keeper/power_dist_change_test.go
- x/finality/keeper/power_table_test.go
- x/finality/types/expected_keepers.go
- x/finality/types/power_table.go
- x/incentive/keeper/btc_staking_gauge.go
- x/incentive/keeper/reward_tracker_test.go
`EventPowerDistUpdate_SlashedFp` and [`RewardBTCStaking`](https://github.com/babylonlabs-io/babylon/blob/b132d16483d2e12ac68be74a524a4b7121edac65/x/incentive/keeper/btc_staking_gauge.go#L19) are called at different blocks. 
The rewards are being called a few blocks behind and if the slashed fp is pruned in BTC reward tracker data, it fails to find and panics 
On babylond-deployments an fp is being slashed at block height 46, the call of `RewardBTCStaking` happens at Babylon block 48 but is called to distribute rewards of voting power table from block 44 (which didn't had the FP slashed yet) which then checks for fp rewards for the FP that was pruned at the slashing processed event.
```
6:04PM INF finalizing commit of block hash=153E869F7B0056A9CD8208301F2019FFACA2BEFBBB35AEADF70DCA14C15F39 …
```
> fix: slashed fp and BTC rewards tracker

- CHANGELOG.md
- x/finality/keeper/tallying.go
- x/finality/keeper/tallying_test.go
https://github.com/babylonlabs-io/babylon/pull/350 Introduced regression due to change from if/else to switch. `break` which earlier was jumping out of the loop, after change would only exit the `switch` statement. 
Fix:
- add `finalizationLoop` label and use it during `break`
- add proper test to check that finalization in consecutive.
> fix block tally in finality module

- CHANGELOG.md
- x/finality/keeper/tallying.go
- x/finality/keeper/tallying_test.go
https://github.com/babylonlabs-io/babylon/pull/350 Introduced regression due to change from if/else to switch. `break` which earlier was jumping out of the loop, after change would only exit the `switch` statement.
Fix:
- add `finalizationLoop` label and use it during `break`
- add proper test to check that finalization in consecutive.
> Backport / fix block tally in finality module (#374)

- CHANGELOG.md
- x/finality/keeper/rewarding.go
- x/finality/keeper/rewarding_test.go
Prior to this fix, if we had an unfinalized block it would stuck to it as a next block to be rewarded
By using `continue` instead of `break`, if there is any finalized block in the interval (`nextBlockToBeRewarded` and `targetHeight`) it will give out rewards and update the next block to be rewarded
> fix: `HandleRewarding` gaps of unfinalized blocks

- CHANGELOG.md
- x/epoching/keeper/drop_validator_msg_decorator.go
- x/epoching/keeper/drop_validator_msg_decorator_test.go
- fixes epoching ante handler that returned early from ante handler even in case of success validation of staking message
> backport/fix epoching ante handler (#385)

- CHANGELOG.md
- test/e2e/btc_rewards_distribution_e2e_test.go
This minimizes the possibility of querying in different blocks, but actually, there was no way to do multiple queries at the same block with guarantee
Runs: 
- https://github.com/babylonlabs-io/babylon/actions/runs/12658410867/job/35275446958?pr=391
- https://github.com/babylonlabs-io/babylon/actions/runs/12658410867/job/35279742461?pr=391
- https://github.com/babylonlabs-io/babylon/actions/runs/12658410867/job/35280945448?pr=391
> chore: tryfix e2e flunky `TestBTCRewardsDistribution`

- CHANGELOG.md
- crypto/schnorr-adaptor-signature/sig.go
- Improves nonce generation for adaptor signatures
- adds custom data for nonce generation
> backport/Improve nonce generation adaptors (#404)

- CHANGELOG.md
- x/btcstaking/keeper/msg_server_test.go
Fixes: https://github.com/babylonlabs-io/babylon/issues/407
Reason of failure: Some times delegation was created below not-deep enough below the tip to be sucessful accepted
> chore: fix flaky test `FuzzCreateBTCDelegationWithParamsFromBtcHeight` 

- CHANGELOG.md
- x/btcstaking/keeper/msg_server_test.go
Fixes: https://github.com/babylonlabs-io/babylon/issues/407
Reason of failure: Some times delegation was created below not-deep enough below the tip to be sucessful accepted
> Backpor: fix flaky test `FuzzCreateBTCDelegationWithParamsFromBtcHeight`

- CHANGELOG.md
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
- proto/buf.lock
All of our modules in proto have `/proto/babylon/<module-name>/v1/files` but incentives does not have `v1` it is defined as `/proto/babylon/incentive/files`
Future investigation to try to add `v1` to the incentive proto will be done at https://github.com/babylonlabs-io/babylon/issues/442
> fix: swagger doc gen incentive v1

- CHANGELOG.md
- x/btclightclient/keeper/msg_server_test.go
- x/btclightclient/types/btc_light_client.go
- x/btclightclient/types/errors.go
Fixes: https://github.com/babylonlabs-io/pm/issues/159
We will reject BTC forks, if the first header is already known. 
This is consensus breaking change, but on our testnet it should be non-breaking as our vigilante reporter always reports only new btc headers prefix/
> Reject forks if the first header is already known

- CHANGELOG.md
- x/btclightclient/keeper/msg_server_test.go
- x/btclightclient/types/btc_light_client.go
- x/btclightclient/types/errors.go
Fixes: https://github.com/babylonlabs-io/pm/issues/159
We will reject BTC forks, if the first header is already known.
This is consensus breaking change, but on our testnet it should be non-breaking as our vigilante reporter always reports only new btc headers prefix/
> Backport: Reject forks if the first header is already known (#445)

- CHANGELOG.md
- app/upgrades/v1/mainnet/btcstaking_params.go
- btcstaking/staking.go
- btcstaking/staking_test.go
- btcstaking/types.go
- btcstaking/types_test.go
- testutil/btcstaking-helper/keeper.go
- x/btcstaking/types/genesis_test.go
- x/btcstaking/types/params.go
- x/btcstaking/types/params_test.go
closed: https://github.com/babylonlabs-io/pm/issues/182
Changes:
- allow slashing rate to have 4 decimal places
- add parameter validation to check whether minimal slashing output is not dust under BTC standard rules
> allow 4 decimal places in  slashing rateparamter

- CHANGELOG.md
- app/include_upgrade_testnet.go
- app/upgrades/v1rc5/testnet/upgrade.go
Adds testnet v1rc5 handler
Note: handler needs to live on main as later when we will be upgrading testnet to v2, the upgrade will need to be made from the latest upgrade on the testnet
> add rc.5 tesnet upgrade handler

- CHANGELOG.md
- app/upgrades/v1/mainnet/btcstaking_params.go
- btcstaking/staking.go
- btcstaking/staking_test.go
- btcstaking/types.go
- btcstaking/types_test.go
- testutil/btcstaking-helper/keeper.go
- x/btcstaking/types/genesis_test.go
- x/btcstaking/types/params.go
- x/btcstaking/types/params_test.go
closed: https://github.com/babylonlabs-io/pm/issues/182
Changes:
- allow slashing rate to have 4 decimal places
- add parameter validation to check whether minimal slashing output is not dust under BTC standard rules
> [Backport-pr491]: allow 4 decimal places in  slashing rateparamter (#491)

- CHANGELOG.md
- test/e2e/btc_staking_e2e_test.go
- test/e2e/btc_staking_pre_approval_e2e_test.go
- test/e2e/configurer/chain/commands_btcstaking.go
- testutil/btcstaking-helper/keeper.go
- testutil/datagen/btcstaking.go
- testutil/datagen/pop.go
- x/btcstaking/keeper/msg_server_test.go
- x/btcstaking/types/pop.go
- x/btcstaking/types/pop_test.go
- x/btcstaking/types/validate_parsed_message_test.go
Part of https://github.com/babylonlabs-io/pm/issues/186
This PR moves PoP constructor functions to `datagen/` package, in order to make it explicit that the constructor functions are only for testing purposes.
> pop: move pop constructor functions to datagen/

- CHANGELOG.md
- x/btcstaking/keeper/btc_consumer_delegations.go
- x/btcstaking/keeper/grpc_query.go
- x/btcstaking/keeper/grpc_query_test.go
fixes: https://github.com/babylonlabs-io/babylon/issues/503
Every query was using latest params to compute wheter delegation is active instead of params related to delegation version.
This could lead to not returnig certain results in case of updating covenant quorum.
> fix status field in rpc api

- CHANGELOG.md
- x/btcstaking/keeper/grpc_query.go
- x/btcstaking/keeper/grpc_query_test.go
fixes: https://github.com/babylonlabs-io/babylon/issues/503 Every query was using latest params to compute wheter delegation is active instead of params related to delegation version.
This could lead to not returnig certain results in case of updating covenant quorum.
> [Backport]: Fix status field in rpc api (#505)

- .github/workflows/backport.yml
This PR fixes the backport action. The action is now using https://github.com/sorenlouv/backport-github-action. According to the doc will submit a backport PR to `release/v1.x` upon merging a PR with label like `backport release/v1.x`.
Not sure how to test this before merging it though
> fix: fix backport Github action

- CHANGELOG.md
- app/signer/bls.go
- app/signer/bls_test.go
- cmd/babylond/cmd/cmd_test.go
- cmd/babylond/cmd/root.go
- Adds `--bls-password` and `--bls-no-password` to start command.
- Default behaviour is to provide a password before node starts for bls signer.
> fix: Add bls signer to start command with password options

- CHANGELOG.md
- x/checkpointing/keeper/keeper.go
- x/checkpointing/keeper/keeper_test.go
- Add missing hook invocation which was marked in coinspect audit as security vuln .
Marked as consensus breaking as other module `x/monitor` depends on this hooks to clear its storage.
> [Backport] add missing hook invocation (#539)

- .github/workflows/backport.yml
This PR fixes the backport Github action. The problem is that the prefix cannot contain any space. Now changed to use prefix `backport-to-`
test plan: Tried on my own branch and there is a successful PR created by GH action https://github.com/babylonlabs-io/babylon/pull/548
> ci: fix backport

- CHANGELOG.md
- x/finality/keeper/msg_server.go
- x/finality/keeper/power_dist_change_test.go
Resolves https://github.com/babylonlabs-io/pm/issues/215
> [Backport] finality: avoid refunding finality signatures over forks (#592)

- CHANGELOG.md
- app/signer/bls.go
Already backported this change after noticing a failed e2e upgrade test in #610 just so main is up to date. Adding case where empty string is somehow inserted into the `app.toml` by mistake or intentionally.
> fix: bls key check for empty string

- CHANGELOG.md
- x/incentive/keeper/genesis.go
- x/incentive/keeper/keeper.go
- x/incentive/keeper/reward_tracker_store.go
This PR reverts the changes introduced [in this PR](https://github.com/babylonlabs-io/babylon/pull/604) that were needed to fix compilation in the `DelegationRewards` tests.
This PR does not need to be backported to the `release/v1.x` branch because the collections are already private there, and the [PR backporting the `DelegationRewards`](https://github.com/babylonlabs-io/babylon/pull/621) changes to the release branch already have the tests fixed
> chore(x/incentive): make keeper collections private

- CHANGELOG.md
- testutil/btcstaking-helper/keeper.go
- x/finality/keeper/power_dist_change.go
- x/finality/keeper/power_dist_change_test.go
- x/finality/types/expected_keepers.go
- x/finality/types/mocked_keepers.go
- We should ignore delegation event in case of lack of covenant quorum. If there was not covenant quorum it means delegaiton was never activated and sats were never counted towards fp
> ignore expire events when there is no covenant quorum

- CHANGELOG.md
- btcstaking/identifiable_staking.go
Helps btc-staker to get parse the tx without verifying the op return tag
> chore: add `ParseV0StakingTxWithoutTag`

- CHANGELOG.md
- crypto/bls12381/bls.go
- crypto/bls12381/types_bench_test.go
Closes https://github.com/babylonlabs-io/pm/issues/288. Group check is necessary to ensure security in BLS verification and aggregation with light loss of performace. Benchmark is attatched in this PR. Bench march results show that the overhead of enabling group check in sig verification is negligible, while in aggregation the time is increased by 2 times (aggregating 100 public keys). Given that aggregation cost is not high and only happens at epoch bondary, the overhead is acceptable.
Benchmark results:
```
goos: darwin
goarch: arm64
pkg: github.com/babylonlabs-io/babylon/crypto/bls12381
cpu: Apple M1 Pro
BenchmarkVerifyCompressed
BenchmarkVerifyCompressed/WithSigGroupCheck
BenchmarkVerifyCompressed/WithSigGroupCheck-8         	    1892	    686257 ns/op …
```
> crypto: Enable group check in BLS

- CHANGELOG.md
- crypto/bls12381/bls.go
- crypto/bls12381/types_bench_test.go
Closes https://github.com/babylonlabs-io/pm/issues/288. Group check is necessary to ensure security in BLS verification and aggregation with light loss of performace. Benchmark is attatched in this PR. Bench march results show that the overhead of enabling group check in sig verification is negligible, while in aggregation the time is increased by 2 times (aggregating 100 public keys). Given that aggregation cost is not high and only happens at epoch bondary, the overhead is acceptable.
Benchmark results:
```
goos: darwin
goarch: arm64
pkg: github.com/babylonlabs-io/babylon/crypto/bls12381
cpu: Apple M1 Pro
BenchmarkVerifyCompressed
BenchmarkVerifyCompressed/WithSigGroupCheck
BenchmarkVerifyCompressed/WithSigGroupCheck-8         	    1892	    686257 ns/op …
```
> [backport] crypto: Enable group check in BLS (#667)

- CHANGELOG.md
- crypto/bip322/bip322.go
- crypto/bip322/bip322_test.go
- testutil/datagen/pop.go
fixes: https://github.com/babylonlabs-io/pm/issues/299
> [Backport] move bip322 signing functions to testutil package (#673)

- CHANGELOG.md
- crypto/eots/eots.go
Closes https://github.com/babylonlabs-io/pm/issues/294. The recomended solution is to always do `negate` and pick the correct value using constant-time conditional select.
> crypto: fix eots signing timing attack

- CHANGELOG.md
- app/signer/types.go
- crypto/bls12381/bls.go
- crypto/bls12381/bls_test.go
- crypto/bls12381/types.go
- crypto/bls12381/types_bench_test.go
- x/checkpointing/types/pop.go
Closes https://github.com/babylonlabs-io/pm/issues/289. Below is what is recomended to fix the issue which the reviewer should follow to check:
1. For signatures, use the domain separation tag specified for the PoP ciphersuite in the BLS specification:
BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_POP_
2. Expose PopProve and PopVerify functions distinct from the standard Sign and Verify functions, and use them when creating all proofs of possession. For these functions, use the domain separation tag specified for PopProve and PopVerify in the BLS spec:
BLS_POP_BLS12381G1_XMD:SHA-256_SSWU_RO_POP_
3. In the BuildPoP function in [app/signer/types.go](https://github.com/babylonlabs-io/babylon/blob/9b91aec647f158e6070ac51272dc6d16e9ed45a0/app/signer/types.go#L50), use the PopProve function described …
> [backport] crypto: fix bls rogue attack (#680)

- go.mod
- go.sum
blst v0.3.14 fixed the binding issue with go 1.24 https://github.com/supranational/blst/releases/tag/v0.3.14
> chore: Upgrade blst

- CHANGELOG.md
- crypto/eots/eots.go
- types/btc_schnorr_pub_rand.go
- types/btc_schnorr_pub_rand_test.go
- x/finality/types/finality.go
- x/finality/types/msg.go
Closes https://github.com/babylonlabs-io/pm/issues/291.
In current EOTS operations, normalized `secp256k1.FieldVal` is required, however, the input is not ensured to meet this condition. This PR fixed the issue by adding normalization in type conversion.
> crypto: fix EOTS missing normalization in use of secp256k1.FieldVal

- crypto/bls12381/bls.go
- crypto/eots/eots.go
Closes https://github.com/babylonlabs-io/pm/issues/293.
This PR added zeroization for secrets in operations of BLS and EOTS. Secret zerioization issues in common and adaptor signatures are handled in other PRs.
> crypto: fix missing secret zeroized

- CHANGELOG.md
- x/btccheckpoint/keeper/msg_server.go
- x/btccheckpoint/keeper/msg_server_test.go
- x/btccheckpoint/keeper/submissions.go
- x/btccheckpoint/types/mock_keepers.go
Improves behaviour when receiving conflicting checkpoints:
- we do not panic if epoch is already finalized
- to preserve panicking behaviour we should succed the transactions which provided us conflicting chekcpoint
> improve checkpoint panic behaviour

- CHANGELOG.md
- x/btccheckpoint/keeper/msg_server.go
- x/btccheckpoint/keeper/msg_server_test.go
- x/btccheckpoint/keeper/submissions.go
- x/btccheckpoint/types/mock_keepers.go
Improves behaviour when receiving conflicting checkpoints:
- we do not panic if epoch is already finalized
- to preserve panicking behaviour we should succed the transactions which provided us conflicting chekcpoint
> [Backport] improve checkpoint panic behaviour (#695)

- CHANGELOG.md
- x/epoching/abci.go
- x/epoching/keeper/msg_server_test.go
We might want to keep our events emitting `EventHandleQueuedMsg` in case of success, if that is needed further tests should be done
> fix: emit double events in queued msgs at end epoch

- CHANGELOG.md
- x/epoching/abci.go
- x/epoching/keeper/msg_server_test.go
We might want to keep our events emitting `EventHandleQueuedMsg` in case of success, if that is needed further tests should be done
---------
> [Backport] fix: emit double events in queued msgs at end epoch (#712)

- CHANGELOG.md
- app/signer/bls.go
- crypto/bls12381/types.go
Closes https://github.com/babylonlabs-io/pm/issues/295. Closes https://github.com/babylonlabs-io/pm/issues/285. The recommendation is to ensure the BLS key loaded from ERC-2335 keystore is a fixed length, i.e., 32 bytes.
> [backport] crypto: Add bls key length validation from the ERC-2335 keystore (#705)

- CHANGELOG.md
- client/config/babylon_config.go
- Default value of `BlockTimeout` was `0` and this makes any tx broadcasted in block mode fail immediately. This was found when debugging https://github.com/babylonlabs-io/babylon-sdk/pull/95
- The `Validate()` function only ensured `BlockTimeout` is not negative. Rather it should be positive and cannot be 0
> chore: fix block timeout in Babylon client

- CHANGELOG.md
- client/config/babylon_config.go
- Default value of `BlockTimeout` was `0` and this makes any tx broadcasted in block mode fail immediately. This was found when debugging https://github.com/babylonlabs-io/babylon-sdk/pull/95
- The `Validate()` function only ensured `BlockTimeout` is not negative. Rather it should be positive and cannot be 0
> [backport] chore: fix block timeout in Babylon client

- CHANGELOG.md
- x/finality/abci.go
- x/finality/keeper/gov.go
- x/finality/keeper/gov_test.go
- x/finality/keeper/rewarding.go
- x/finality/keeper/rewarding_test.go
- x/finality/keeper/tallying.go
- x/finality/keeper/tallying_bench_test.go
- x/finality/keeper/tallying_test.go
- x/finality/types/constants.go
- x/finality/types/finality.go
Add limit to number of finalized and rewarded blocks per call. This is needed to limit unbounded block processing times in case of finality stalling
> limit number of finalized and rewarded blocks

- CHANGELOG.md
- app/include_upgrade_mainnet.go
- app/include_upgrade_testnet.go
- app/upgrades/v1/data_params_test.go
- app/upgrades/v1/data_token_distribution_test.go
- app/upgrades/v1/mainnet/btcstaking_params.go
- app/upgrades/v1/mainnet/finality_params.go
- app/upgrades/v1/mainnet/incentive.go
- app/upgrades/v1/mainnet/params_update.go
- app/upgrades/v1/mainnet/token_distribution.go
- app/upgrades/v1/testnet/params_update.go
- app/upgrades/v1/upgrades.go
- app/upgrades/v1/upgrades_test.go
Add parameters in the upgrade handler as the spec and global parameters for `bbn-1`
Removed prefix `Testnet` and `Mainnet` in v1 upgrade data packages
> chore: upgrade parameters

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- CHANGELOG.md
- Makefile
- Fix build tag in version, now it appears testnet or mainnet with `version --long`
```shell
build_tags: netgo,ledger,testnet
commit: 931c61a1d39ef1adbdaf671be72cd367694f0b08
cosmos_sdk_version: v0.50.12
go: go version go1.23.1 linux/amd64
name: babylon
server_name: babylond
version: rafilx/go-releaser-test-931c61a1d39ef1adbdaf671be72cd367694f0b08
```
- Statically links wasm in release assets
- Creates one binary with testnet build tag and another for mainnet
> chore: go releaser testnet + wasm statically

- CHANGELOG.md
- app/upgrades/v1/mainnet/params_update.go
- app/upgrades/v1/upgrades_test.go
- testutil/sample/sample.go
- Base BTC header in v0.9.3 is height [`854784`](https://mempool.space/block/0000000000000000000289d41c5b01a89982a510f9c49d730eaa328d0abbfbcb) header: `0000c020f382af1f6d228721b49f3da2f5b831587803b16597b301000000000000000000e4f76aae64d8316d195a92424871b74168b58d1c3c6988548e0e9890b15fc2fc3c00aa66be1a0317082e4bc7`
- The BTC headers inserted in the upgrade are from [`854785`](https://mempool.space/block/0000000000000000000118c1e53554dac0d9da7717587d3cdb72d458df9dbb12) to [`890123`](https://mempool.space/block/00000000000000000001fd463e1125fd67db97fd9e52cb3efe532f9b170ad658)
> chore: add BTC headers from `854785` to `890123`

- x/btcstaking/docs/registration-eligibility.md
- Capitalized 'Finality Providers'
- Corrected spelling 'stake'
- Used 'Babylon Genesis' instead of Babylon chain when referring to mainnet
- Consistent capitalization of "Phase-1" in all instances
- Rephrased sections for better clarity and flow
> Fix: typo edits registration-eligibility.md

- .goreleaser.yml
- CHANGELOG.md
- Add `mainnet` build tag, since goreleaser is not using make to build, it needs to add mainnet manually
> fix: goreleaser for mainnet

- CHANGELOG.md
- app/app_test.go
- app/encoding.go
- cmd/babylond/cmd/genhelpers/gentx_test.go
- cmd/babylond/cmd/testnet_test.go
- testutil/keeper/btclightclient.go
fixes: https://github.com/babylonlabs-io/babylon/issues/801
`TmpAppOptions` allocates external resources without giving the caller opportunity to clean them up. This pr changes that by also returning cleanup funciton for the caller to run when necessary.
> clean up resources from TmpAppOptions

- test/replay/app_replay_e2e_test.go
- test/replay/btcstaking_test.go
- test/replay/covenant_sender.go
- test/replay/driver.go
- test/replay/driver_queries.go
- test/replay/finality_provider_sender.go
- test/replay/finality_test.go
- test/replay/replayer.go
- test/replay/scenario_builder.go
- test/replay/staker_sender.go
- testutil/datagen/btcstaking.go
- x/finality/keeper/power_dist_change_test.go
Extends testing framework for deterministic cross module integration test to enable finality voting.
Also add nicer api to simulate operatoins mimicking how they happen in practice.
Use cases for this framework:
- cross module integration tests checking edge case scenarios
- replay tests to check determinism of particular scenarios
> Framework for determinisitc tests for btcstaking protocol

- CHANGELOG.md
- cmd/babylond/cmd/cmd_test.go
- test/e2e/initialization/config.go
- test/replay/app_replay_e2e_test.go
- test/replay/btcstaking_test.go
- test/replay/covenant_sender.go
- test/replay/driver.go
- test/replay/driver_queries.go
- test/replay/finality_provider_sender.go
- test/replay/finality_test.go
- test/replay/gov.go
- test/replay/replayer.go
- test/replay/scenario_builder.go
- test/replay/staker_sender.go
- testutil/datagen/btcstaking.go
- x/finality/keeper/gov.go
- x/finality/keeper/gov_test.go
- x/finality/keeper/power_dist_change_test.go
Prior to this, any slashed FP at the latest height wouldn't be jailed and the proposal would fail
Add checks for FP slash and only set in vp distribution cache to jailed if it wasn't already slashed
Also had to update replay driver code to run tests
Backport: #829
> backport(bugfix): add checks for slashed fp in gov resume finality (#829) 

- CHANGELOG.md
- cmd/babylond/cmd/cmd_test.go
- test/e2e/initialization/config.go
- test/replay/app_replay_e2e_test.go
- test/replay/btcstaking_test.go
- test/replay/covenant_sender.go
- test/replay/driver.go
- test/replay/driver_queries.go
- test/replay/finality_provider_sender.go
- test/replay/finality_test.go
- test/replay/gov.go
- test/replay/replayer.go
- test/replay/scenario_builder.go
- test/replay/staker_sender.go
- testutil/datagen/btcstaking.go
- x/finality/keeper/gov.go
- x/finality/keeper/gov_test.go
- x/finality/keeper/power_dist_change_test.go
Prior to this, any slashed FP at the latest height wouldn't be jailed and the proposal would fail
Add checks for FP slash and only set in vp distribution cache to jailed if it wasn't already slashed
Also had to update replay driver code to run tests
Backport: #829
> backport(bugfix): add checks for slashed fp in gov resume finality (#829)

- CHANGELOG.md
- app/keepers/keepers.go
- app/params/config.go
- go.mod
Wiring based on : https://github.com/cosmos/ibc-go/blob/modules/apps/callbacks/v0.2.0%2Bibc-go-v8.0/modules/apps/callbacks/testing/simapp/app.go#L511
As IBC-callbacks are stateless, no upgrade is needed
> feat: Wire up ibc callbacks

- CHANGELOG.md
- client/query/client.go
- client/query/epoching.go
- test/replay/driver.go
- test/replay/finality_test.go
- test/replay/scenario_builder.go
- x/finality/keeper/gov.go
- x/finality/keeper/gov_test.go
- x/finality/keeper/power_dist_change.go
It is possible that some inactive fps become active after executing the finality resumption proposal. However, current implementation does not initiate signing info for those fps, which would cause panicking when handling liveness.
This PR fixed the issue by ensuring every active finality provider has signing info in the finality resumption proposal.
> fix: ensure active fps have signing info after proposal

- CHANGELOG.md
- go.mod
- go.sum
Bumps tokenfactory version to v0.50.6 where a convenience query was added:
- `denoms-from-admin`: Returns a list of all denoms for which a given address is the admin.
> chore: bump tokenfactory version

- .github/workflows/release.yml
When a release is created using the [release workflow](https://github.com/babylonlabs-io/babylon/blob/main/.github/workflows/release.yml), it doesn't trigger the gorelease workflow due to the limitation with `github.token` ([ref](https://github.com/actions/create-release/issues/71)).
This PR moves the goreleaser job into the release workflow, allowing it to be executed once the release is created
> chore: move goreleaser job to release workflow

- CHANGELOG.md
- app/upgrades/v2/upgrades.go
- test/e2e/software_upgrade_e2e_v2_test.go
Updates params in upgrade to use `ubbn` as fee denom and default amounts
> fix: update tokenfactory params to use `ubbn` as fee denom

- CHANGELOG.md
- app/signer/bls.go
- app/signer/bls_test.go
- app/signer/util.go
- cmd/babylond/cmd/root.go
- cmd/babylond/cmd/update_bls_password.go
This PR includes the following changes:
- The existing password must be provided either via an interactive prompt or through the environment variable. For the security issue, existing password cannot be obtained by file.
- If previous version of BLS key does not have a password, enter empty value into prompt.
- The new password is managed using the same set of flags that are used when initially generating a BLS key.
- Users are asked to process updating password of BLS since `bls_key.json` is overwritten with new password.
- The `BABYLON_BLS_PASSWORD` environment variable is used to load the existing password. After running `update-bls-password`, users should update this variable to reflect the new password.
- Since both `bls_key.json` and its associated password file are set to read-only …
> [backport] feat: create update-bls-password cmd (#871)

- docs/register-bitcoin-stake.md
- Consistent Capitalization for "Finality Providers" "Vigilante Watcher" "Phase-1"
- Clarified use of "Babylon Genesis" when referring to the mainnet chain
- Corrected spelling of "minimum"
> Fix: typo register-bitcoin-stake.md edits

- CHANGELOG.md
- x/finality/types/signing_info.go
- x/finality/types/signing_info_test.go
validation of `StartHeight` and `MissedBlockCounter` are greater than or equal to zero
> fix: signing info validation for start height and missed block counter

- CHANGELOG.md
- app/ante/ibc_msg_size.go
- app/ante/ibc_msg_size_test.go
3. Missing message size enforcement in DeliverTx enables
oversized IBC messages payload injection
In babylon:app/ante/ibc_msg_size.go:25-44, the AnteHandle function of the
IBCMsgSizeDecorator validates IBC message size constraints only during the CheckTx
phase.
This validation includes limits on message, memo, and address sizes for MsgTransfer and
MsgSendTx messages.
However, no equivalent enforcement occurs during the DeliverTx phase, which is
responsible for block execution.
As a result, malicious proposers can bypass mempool checks and inject oversized IBC or ICA
messages directly into blocks without the risk of being slashed.
This forces other validators to process potentially resource-exhausting payloads, introducing
a denial of service vector within the consensus mechanism.
> fix: enforce check tx even without check tx

- CHANGELOG.md
- x/finality/types/genesis_test.go
- x/finality/types/power_table.go
- x/finality/types/power_table_test.go
Address needed to be validated if empty and if it is indeed a bech32 type
> chore: update `fpdistributioninfo` validations

- testutil/keeper/btccheckpoint.go
- x/btccheckpoint/keeper/genesis_test.go
- x/btcstaking/genesis_test.go
This was already fixed in the backports
https://github.com/babylonlabs-io/babylon/pull/1115
> fix: TestGenesis in btcstaking

- CHANGELOG.md
- x/incentive/keeper/genesis_test.go
- x/incentive/types/genesis.go
- x/incentive/types/genesis_test.go
validation to ensure each finality provider has historical rewards entries for all periods from 0 through `FinalityProviderCurrentRewards.Period - 1`
> fix: validate genesis fp historic reward entries

- CHANGELOG.md
- x/epoching/types/epoching.go
- x/epoching/types/epoching_test.go
20. Missing validation of the Power field of a Validator may result in potential overflows
> chore: validate power non negative

- CHANGELOG.md
- app/app.go
- app/export.go
- app/keepers/keepers.go
- app/upgrades/v2/upgrades.go
- app/upgrades/v2/upgrades_test.go
- app/upgrades/v2rc2/testnet/upgrade.go
- cmd/babylond/cmd/genesis.go
- cmd/babylond/cmd/root.go
- test/e2e/initialization/config.go
`x/crisis` module became [deprecated](https://github.com/cosmos/cosmos-sdk/blob/810d15dd6d16084c9ba6dfc018e9431172cd4786/x/crisis/README.md?plain=1#L7)
sec 9. Usage of deprecated x/crisis module allows attackers to DoS the chain
> chore: remove `x/crisis`

- CHANGELOG.md
- app/include_upgrade_mainnet.go
- app/include_upgrade_testnet.go
- app/upgrades/v2/upgrades.go
- app/upgrades/v2/upgrades_test.go
32. Upgrade handler channel rate limiting enables denial of service via channel spam
> chore: add whitelisted channels to add rate limit

- CHANGELOG.md
- app/ante/ibc_msg_size.go
43. The MaxAddressSize constant is excessively large
> chore: reduced ibc `MaxAddressSize` to max value of bech 32 addr (90)

- CHANGELOG.md
- x/checkpointing/keeper/grpc_query_bls.go
- x/checkpointing/keeper/grpc_query_bls_test.go
- x/checkpointing/types/bls_key.go
x/checkpointing/keeper/grpc_query_bls.go
Keeper.BlsPublicKeyList does not validate pagination inputs when there are zero validators for a given epoch. By passing offset > 0 on an empty result set, the code computes total-1 where total == 0, underflows, and proceeds to slice an empty Go slice and triggers a panic.
How to replicate:
```shell
grpcurl -plaintext -d '{"epoch_num":999,"pagination":{"offset":1,"limit":1}}' localhost:9090 babylon.checkpointing.v1.Query/BlsPublicKeyList
```
> fix: checks for pagination in `QueryBlsPublicKeyListRequest`

- CHANGELOG.md
- proto/babylon/zoneconcierge/v1/packet.proto
- x/zoneconcierge/README.md
- x/zoneconcierge/types/packet.pb.go
This PR does a quick tidyup for x/zoneconceirge module doc. This includes:
- removing the usage of legacy terms
- removing the outdated concept section (will follow up with a new one in subsequent PRs)
- adding a new section briefly discussing BTC staking integration
Subsequent PRs will add more technical details.
> doc: revise zone concierge doc (round 1)

- CHANGELOG.md
- app/keepers/keepers.go
- x/zoneconcierge/module_ibc.go
- x/zoneconcierge/types/mocked_keepers.go
was getting this in local deployment then realized, ibc router is missing for zc
```
→ Creating IBC channel for zoneconcierge...
2025-06-19T19:17:39.981605Z	info	Starting event processor for channel handshake	{"src_chain_id": "chain-test", "src_port_id": "zoneconcierge", "dst_chain_id": "bcd-test", "dst_port_id": "wasm.bbnc14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9syx25zf"}
2025-06-19T19:17:39.983040Z	info	Chain is in sync	{"chain_name": "bcd", "chain_id": "bcd-test"}
2025-06-19T19:17:39.983944Z	info	Chain is in sync	{"chain_name": "babylon", "chain_id": "chain-test"}
2025-06-19T19:17:50.222487Z	error	Error sending messages	{"path_name": "bcd", "src_chain_id": "bcd-test", "dst_chain_id": "chain-test", "src_client_id": "07-tendermint-0", "dst_client_id": "07-tendermint-0", …
```
> fix: zoneconcierge ibc router

- CHANGELOG.md
- test/replay/btcstaking_test.go
- test/replay/finality_test.go
- test/replay/multistaking_test.go
- x/btcstaking/keeper/finality_providers.go
- x/finality/keeper/grpc_query.go
- x/finality/keeper/grpc_query_test.go
- x/finality/keeper/msg_server.go
- x/finality/keeper/msg_server_test.go
- x/finality/keeper/power_dist_change.go
- x/finality/keeper/power_table.go
- x/finality/types/expected_keepers.go
- x/finality/types/mocked_keepers.go
In some places check `k.BTCStakingKeeper.HasFinalityProvider` was overloaded to mean `is is Babylon finality provider` as only `BTCStakingKeeper` stored Babylon finality providers.  https://github.com/babylonlabs-io/babylon/pull/1300 moved all finality providers to the `BTCStakingKeeper`, so the overloaded check lost its power. 
This could lead to non-Babylon finality providers registering randomness and gaining voting power on Babylon genesis.
> fix: do not add multistaked fps to voting table

- .github/workflows/ci.yml
The current setting will only run builds for branches created directly on the babylon repo. Adding this condition ensures that CI will run on all PRs, originating either from this repo or forked ones.
> chore: ci/cd: Run builds on forked PRs

- CHANGELOG.md
- x/btcstaking/keeper/finality_providers.go
- x/btcstaking/keeper/genesis.go
- x/btcstaking/keeper/migrations.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/migrations/v2/store.go
- x/btcstaking/migrations/v2/store_test.go
- x/btcstkconsumer/keeper/msg_server.go
- x/btcstkconsumer/keeper/msg_server_test.go
- x/btcstkconsumer/types/consumer_register.go
Closes: https://github.com/babylonlabs-io/babylon/issues/1306
After multi-staking launch, finality providers that secure Babylon should be identifies by Babylon Genesis chain-id. To achieve that for pre-upgrade FPs migration is needed.
This pr:
- adds proper migration for FP data
- add migration to add Babylon FPs to newly added index
- add additional validation that `ConsumerId` is valid utf8 string. This is needed as the field is used as key in index.
- add additional validation that registered `ConsumerId` is not Babylon chain id.
> migration of FP data

- CHANGELOG.md
- docs/ibc-zoneconcierge-setup.md
- x/zoneconcierge/README.md
Resolves https://github.com/babylonlabs-io/pm/issues/459
This PR provides doc for setting up a Zone Concierge IBC channel. 
As a first version, the doc is kept minimal, in the sense that it focuses on unique characteristics of zone concierge IBC channel, and refers to external docs for Zone Concierge module, BTC staking, IBC relayer operation guides, etc..
> doc: zone concierge IBC channel doc

- CHANGELOG.md
- test/e2e/configurer/current.go
- test/e2e/initialization/chain/main.go
- test/e2e/initialization/config.go
- test/e2e/initialization/init.go
- test/e2e/initialization/init_test.go
- test/e2e/initialization/node.go
- test/replay/driver.go
- test/replay/multistaking_test.go
- test/replay/replayer.go
- x/btcstaking/keeper/btc_delegations.go
- x/btcstaking/keeper/btc_staking_consumer_events.go
- x/btcstaking/keeper/inclusion_proof.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/types/params.go
Currently in case of IBC packet being to large, Babylon waould just fail to send it and later delete it:
- [error](https://github.com/babylonlabs-io/babylon/blob/v3.0.0-snapshot.250731/x/zoneconcierge/keeper/ibc_packet.go#L80)
- [deletion](https://github.com/babylonlabs-io/babylon/blob/v3.0.0-snapshot.250731/x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go#L94)
This behaviour would lead to incorrect accounting of voting power on consumer chain.
Given that creating such packet requires tightly packing delegation activations in one Babylon block, it could on exploited by malicious validator and has low chance of being triggered in normal operations.
This PR:
- adds test showing that it is in fact possible to create invalid too big packet
- adds fail safe limit making it …
> add limit for ibc packet

- CHANGELOG.md
- x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
Closes: #1454
Restore the assignment of `finalizedHeader.Proof` to `btcTimestamp.Proof.ProofConsumerHeaderInEpoch`, which was removed in PR [#1387](https://github.com/babylonlabs-io/babylon/pull/1387/files#diff-3fd29e097d45a0f042e4cf72768de74dc135d28987c48ec04133f761c88d2d16L131-R130) during recent refactoring.
This change addresses the issue where `proof_consumer_header_in_epoch` field in IBC packets is sometimes empty, as reported in #1454.
- While investigating issue #1454, it was suspected that the refactoring in PR [#1387](https://github.com/babylonlabs-io/babylon/pull/1387/files#diff-3fd29e097d45a0f042e4cf72768de74dc135d28987c48ec04133f761c88d2d16L131-R130) accidentally removed the assignment:
`btcTimestamp.Proof.ProofConsumerHeaderInEpoch = finalizedHeader.Proof` …
> fix: restore proofConsumerHeaderInEpoch allocation removed in PR #1387

- docs/ibc-zoneconcierge-setup.md
This PR provides a second revision of zone concierge IBC channel doc. It
- introduces a new section for describing the steps of creating zone concierge IBC channel in detail
- adds some justifications on why the steps are necessary
> doc: zc IBC channel doc revision

- CHANGELOG.md
- app/upgrades/delete_dup_fp.go
- app/upgrades/v2_3/upgrades.go
- app/upgrades/v3rc3/upgrades.go
- app/upgrades/v3rc3/upgrades_test.go
- x/btcstaking/types/keys.go
- Update Testnet upgrade `v3rc3` to bring back `LargestBtcReorg` to prefix number 11
> fix: `LargestBtcReorg` prefix to follow mainnet

- test/replay/btcstaking_test.go
- test/replay/costaking.go
- test/replay/costaking_test.go
- test/replay/driver.go
- test/replay/multistaking_test.go
- test/replay/stake_expansion_test.go
- test/replay/staker_sender.go
- x/finality/keeper/power_dist_change.go
- x/finality/keeper/power_dist_change_test.go
- x/finality/types/power_table.go
- x/finality/types/power_table_test.go
Modified `GetInactiveFinalityProviderSet` to return jailed and slashed fp as well, check is now done at `HandleFPStateUpdates` after calling hooks but prior to emit block events
> fix: costaking find inactive returns slashed and jailed

- CHANGELOG.md
- app/include_upgrade_testnet.go
- app/upgrades/epoching/validation.go
- app/upgrades/v3/upgrades.go
- app/upgrades/v3/upgrades_test.go
- app/upgrades/v3rc4/testnet/upgrades.go
- app/upgrades/v3rc4/testnet/upgrades_test.go
- test/e2e/configurer/upgrade.go
- test/e2e/govProps/v3.json
- x/epoching/types/expected_keepers.go
Closes: #1662 
Add upgrade handler logic to enable epoching spam prevention.
**Testnet:** upgrade handler applied in v3rc4
**Mainnet:** upgrade handler applied in v3
**Upgrade must occur at the first block of the epoch; if the block number is incorrect, the upgrade fails.**
- Add v3rc4/upgrades.go: upgrade logic for testnet.
- Add v3rc4/upgrades_test.go: upgrade test code.
- Add validation.go: common validation logic for upgrade.
- Modify v3/upgrades.go: add validation logic for epoching spam prevention upgrade.
- Modify v3/upgrades_test.go: fix dummyUpgradeHeight to first block of epoch, add validation for epoching.
- Modify e2e/configurer/upgrade.go: fix ChainConfig.UpgradeHeight to first block of epoch.
> Add : Upgrade handler for epoching spam prevention (#1663)

- x/checkpointing/README.md
https://docs.babylonlabs.io/docs/developer-guides/modules/reporter - broken
https://docs.babylonlabs.io/guides/architecture/vigilantes/reporter/ - correct
> docs: fix broken link

- CHANGELOG.md
- test/replay/costaking_test.go
- x/costaking/keeper/hooks_staking.go
- x/costaking/types/staking_cache.go
- x/costaking/types/staking_cache_test.go
Issue case: 
1. Del1 baby stake to val1 10BABY
2. Del1 baby unbond from val1 10BABY
3. Del1 baby stake to val1 25BABY
4. Active BABY would result in 15BABY 
The stk cache was not being properly cleaned after using it. 
Fix is to clean the pair after using it
> fix: baby staking hooks in costaking deletes StkCache after using
