babylonlabs-io/babylon

docs/transaction-impl-spec.md, x/finality/README.md
Fixed typos to make the documentation clearer. Hope this helps.
=> chore: correction typos

.github/CODEOWNERS
Add codeowners files to the repository
=> feat: Add code owners file

x/btcstaking/types/validate_parsed_message_test.go
Comprehensive table driven test suite to check validations on message validation
Update: upgrade e2e test may still fail, this will be tackled in next pr
=> feat: add comprehensive test suite for staking msg validation

.github/workflows/ci.yml
upgrades CI, should build arm64 images
=> chore(ci): upgrade CI

.github/workflows/publish.yml
=> chore(ci): upgrade publish ci

app/app.go, app/upgrades/signetlaunch/finality_params.go, app/upgrades/signetlaunch/finality_params_test.go, app/upgrades/signetlaunch/upgrades.go, app/upgrades/signetlaunch/upgrades_test.go, app/upgrades/types.go, test/e2e/configurer/chain/queries_btcstaking.go, test/e2e/software_upgrade_e2e_signet_launch_test.go, x/finality/types/keys.go
This is required for upgrading from the TGE chain
=> feat(ADR-25): Add upgrade and test

cmd/babylond/cmd/custom_babylon_config.go, cmd/babylond/cmd/genesis.go, cmd/babylond/cmd/root.go, cmd/babylond/cmd/testnet.go, contrib/images/babylond/Dockerfile, test/e2e/initialization/node.go
=> backport: fix minor issues with testnet command (#91)

CHANGELOG.md
Forgot to add changelog in #91
=> chore: add changelog for pr 91

CHANGELOG.md, contrib/images/babylond/Dockerfile, contrib/images/e2e-initialization/init.Dockerfile, test/e2e/configurer/chain/chain.go, test/e2e/ibc_transfer_e2e_test.go
Merging this to `main` as it can live there as well.
=> Housekeeping: backport IBC transfer e2e

CHANGELOG.md, go.mod, go.sum
- fixes https://github.com/cometbft/cometbft/security/advisories/GHSA-p7mv-53f2-4cwj
=> Bump comet bft version

CHANGELOG.md, x/btcstaking/keeper/msg_server.go, x/btcstaking/keeper/msg_server_test.go, x/btcstaking/types/errors.go
- EOI created delegations parameter version should be the some one for given block range
=> Enforce correct parameters version when verifing EOI

CHANGELOG.md, x/btcstaking/types/genesis.go, x/btcstaking/types/genesis_test.go
=> fix genesis state validation

CHANGELOG.md, x/epoching/keeper/drop_validator_msg_decorator.go, x/epoching/keeper/drop_validator_msg_decorator_test.go
- fixes epoching ante handler that returned early from ante handler even in case of success validation of staking message
=> fix epoching ante handler

CHANGELOG.md
-backport of changelog changes for v1.0.0-rc.3
=> backport/change log  changes v1.0.0-rc.3

CHANGELOG.md, crypto/schnorr-adaptor-signature/sig.go
- Improves nonce generation for adaptor signatures
- adds custom data for nonce generation
=> Improve nonce generation adaptors

CHANGELOG.md, crypto/schnorr-adaptor-signature/sign_utils.go
closes: https://github.com/babylonlabs-io/pm/issues/157
=> Backpot: fix R verification (#413)

CHANGELOG.md, client/babylonclient/chain_provider.go, client/babylonclient/grpc_query.go, client/babylonclient/tx.go, client/client/tx.go
Would help reduce duplication in https://github.com/babylonlabs-io/covenant-emulator/pull/98
=> chore: update cosmos provider to expose public functions

CHANGELOG.md, x/checkpointing/keeper/keeper.go, x/checkpointing/keeper/keeper_test.go
fixes: https://github.com/babylonlabs-io/pm/issues/180
=> fix status check from confirmed checkpoint

CHANGELOG.md, app/ante/fee_checker.go, app/ante/get_tx_priority_test.go, test/e2e/btc_rewards_distribution_e2e_test.go, test/e2e/btc_staking_e2e_test.go, test/e2e/btc_staking_pre_approval_e2e_test.go, test/e2e/configurer/chain/commands.go, test/e2e/configurer/chain/commands_btcstaking.go, test/e2e/configurer/chain/queries.go, test/e2e/containers/containers.go, test/e2e/ibc_transfer_e2e_test.go, test/e2e/initialization/config.go, test/e2e/initialization/node.go, test/e2e/scripts/hermes_bootstrap.sh, x/incentive/types/types.go
Pass 1
https://github.com/babylonlabs-io/babylon/actions/runs/13081416537/job/36505723250 Pass 2
https://github.com/babylonlabs-io/babylon/actions/runs/13081416537/job/36506484641 Pass 3
https://github.com/babylonlabs-io/babylon/actions/runs/13081416537/job/36506854617 Pass 4
https://github.com/babylonlabs-io/babylon/actions/runs/13081416537/job/36507342272 Pass 5
https://github.com/babylonlabs-io/babylon/actions/runs/13081416537/job/36508176401
=> chore: backport e2e rewards test flaky (#421)

CHANGELOG.md, x/checkpointing/keeper/keeper.go, x/checkpointing/keeper/keeper_test.go
fixes: https://github.com/babylonlabs-io/pm/issues/180
=> Backport: fix status check from confirmed checkpoint (#473)

CHANGELOG.md, app/include_upgrade_testnet.go, app/upgrades/v1rc5/testnet/upgrade.go
- Adds testnet v1rc5 upgrade handler
=> [Backport]: add rc.5 tesnet upgrade handler (#493)

CHANGELOG.md, x/btcstaking/client/cli/query.go, x/btcstaking/client/cli/query_params.go
- adds command to retrieve params by version
=> add command to get params by version

CHANGELOG.md, x/btcstaking/client/cli/query.go, x/btcstaking/client/cli/query_params.go
- adds command to retrieve params by version
=> [Backport]:add command to get params by version (#499)

CHANGELOG.md, crypto/ecdsa/ecdsa.go, crypto/ecdsa/ecdsa_test.go
Resolves https://github.com/babylonlabs-io/pm/issues/194
=> crypto: fix ecdsa malleability

CHANGELOG.md, crypto/ecdsa/ecdsa.go, crypto/ecdsa/ecdsa_test.go
Resolves https://github.com/babylonlabs-io/pm/issues/194
=> [Backport] crypto: fix ecdsa malleability (#509)

CHANGELOG.md, x/checkpointing/abci.go, x/checkpointing/keeper/keeper.go, x/checkpointing/keeper/keeper_test.go, x/checkpointing/module.go, x/checkpointing/types/keys.go
Closes: https://github.com/babylonlabs-io/pm/issues/196
=> backport: chore(checkpointing): add ConflictingCheckpointReceived flag (#530)

CHANGELOG.md, app/signer/bls.go, app/signer/bls_test.go, cmd/babylond/cmd/cmd_test.go, cmd/babylond/cmd/root.go
Closes: https://github.com/babylonlabs-io/babylon/issues/514
=> backport: fix: Add bls signer to start command with password options (#527)

CHANGELOG.md, x/checkpointing/proposal.go, x/checkpointing/vote_ext.go
=> chore: Improve vote extension logs

CHANGELOG.md, x/checkpointing/proposal.go, x/checkpointing/vote_ext.go
=> [backport] chore: Improve vote extension logs (#554)

CHANGELOG.md, x/btcstaking/keeper/inclusion_proof.go, x/btcstaking/keeper/inclusion_proof_test.go
closes: https://github.com/babylonlabs-io/babylon/issues/522
=> reject coinbase staking tx

CHANGELOG.md, x/finality/keeper/msg_server.go, x/finality/keeper/msg_server_test.go, x/finality/types/errors.go
Closes https://github.com/babylonlabs-io/pm/issues/248
=> fix(finality): check for overflow in CommitPubRandList

CHANGELOG.md, x/epoching/keeper/hooks.go
Closes: https://github.com/babylonlabs-io/pm/issues/247
=> fix(epoching): remove float values in BeforeValidatorSlashed hook

CHANGELOG.md, x/epoching/keeper/hooks.go
Closes: https://github.com/babylonlabs-io/pm/issues/247
=> backport: fix(epoching): remove float values in BeforeValidatorSlashed hook (#566)

CHANGELOG.md, x/finality/keeper/msg_server.go, x/finality/keeper/msg_server_test.go, x/finality/types/errors.go
Closes https://github.com/babylonlabs-io/pm/issues/248
=> backport: fix(finality): check for overflow in CommitPubRandList (#567)

CHANGELOG.md, x/finality/keeper/liveness.go, x/finality/keeper/power_dist_change_test.go
Closes https://github.com/babylonlabs-io/pm/issues/244#event-16478806435
=> fix: Panic can be triggered in handling liveness

CHANGELOG.md, x/finality/keeper/msg_server.go
Resolves https://github.com/babylonlabs-io/pm/issues/215
=> finality: avoid refunding finality signatures over forks

CHANGELOG.md, test/replay/driver.go, testutil/datagen/btcstaking.go, x/btcstaking/keeper/btc_reorg_test.go, x/finality/keeper/power_dist_change.go, x/finality/keeper/power_dist_change_test.go, x/finality/types/power_table.go, x/finality/types/power_table_test.go
=> chore: backport #579

CHANGELOG.md, proto/babylon/incentive/genesis.proto, x/incentive/keeper/genesis.go, x/incentive/keeper/genesis_test.go, x/incentive/keeper/keeper.go, x/incentive/keeper/reward_tracker_store.go, x/incentive/types/genesis.go, x/incentive/types/genesis.pb.go, x/incentive/types/genesis_test.go, x/incentive/types/rewards.go
This is a follow up of
https://github.com/babylonlabs-io/babylon/pull/519 to add some missing fields in the genesis state
=> backport: chore(x/incentive): add missing data to genesis (#542)

CHANGELOG.md, x/incentive/keeper/keeper_test.go, x/incentive/keeper/refundable_msg_index.go
- in case of fee granter refund fee to the granter
=> refund fee to correct receipient

testutil/keeper/incentive.go, x/finality/keeper/power_dist_change_test.go, x/incentive/keeper/genesis.go, x/incentive/keeper/keeper.go, x/incentive/keeper/reward_tracker_store.go
- https://github.com/babylonlabs-io/babylon/pull/542, broke the build as it was not rebased on https://github.com/babylonlabs-io/babylon/pull/590
=> FIx build on main

CHANGELOG.md, app/signer/bls.go, app/signer/bls_test.go, cmd/babylond/cmd/cmd_test.go, cmd/babylond/cmd/custom_babylon_config.go, cmd/babylond/cmd/root.go
=> chore: backport #544

CHANGELOG.md, client/docs/swagger-ui/swagger.yaml
=> chore: Fix swagger

CHANGELOG.md, client/docs/swagger-ui/swagger.yaml, testutil/datagen/btc_transaction.go, testutil/datagen/btcstaking.go, x/btcstaking/types/btc_delegation.go, x/btcstaking/types/btc_delegation_test.go, x/finality/keeper/power_dist_change_test.go
#597 fix btc expired + unbonding
=> chore: backport #597

CHANGELOG.md, crypto/schnorr-adaptor-signature/keys.go, crypto/schnorr-adaptor-signature/keys_test.go, crypto/schnorr-adaptor-signature/sig.go
Resolves https://github.com/babylonlabs-io/pm/issues/282
=> crypto: check if Z==1 in ToBTCPK

CHANGELOG.md, crypto/schnorr-adaptor-signature/keys.go, crypto/schnorr-adaptor-signature/keys_test.go, crypto/schnorr-adaptor-signature/sign_utils.go, x/btcstaking/keeper/msg_server_test.go, x/btcstaking/types/btc_slashing_tx.go, x/btcstaking/types/btc_slashing_tx_test.go, x/btcstaking/types/btc_undelegation_test.go
Resolves https://github.com/babylonlabs-io/pm/issues/278
Resolves https://github.com/babylonlabs-io/pm/issues/283
=> crypto: fix adaptor sig validity and typos

CHANGELOG.md, crypto/ecdsa/ecdsa.go, crypto/ecdsa/ecdsa_test.go, x/btcstaking/types/pop.go, x/btcstaking/types/pop_test.go
fixes:
- https://github.com/babylonlabs-io/pm/issues/298
- https://github.com/babylonlabs-io/pm/issues/297
=> add function to recover pub key from sig

CHANGELOG.md, crypto/ecdsa/ecdsa.go, crypto/ecdsa/ecdsa_test.go, x/btcstaking/types/pop.go, x/btcstaking/types/pop_test.go
fixes:
- https://github.com/babylonlabs-io/pm/issues/298
- https://github.com/babylonlabs-io/pm/issues/297
=> [Backport ]add function to recover pub key from sig (#660)

CHANGELOG.md, btcstaking/identifiable_staking.go
=> chore: backport `ParseV0StakingTxWithoutTag` (#655)

CHANGELOG.md, crypto/bip322/bip322.go, crypto/bip322/bip322_test.go, testutil/datagen/pop.go
fixes: https://github.com/babylonlabs-io/pm/issues/299
=> move bip322 signing functions to testutil package

CHANGELOG.md, client/client/tx.go
Same as https://github.com/babylonlabs-io/cosmwasm-client/pull/2 but for the babylon client.
=> Add send msg / send msgs helpers to babylon client

crypto/common/common.go
Fixes: https://github.com/babylonlabs-io/pm/issues/303
=> improved randomness generation

RELEASE_PROCESS.md
- Updates release process to take account of major versions
- Add release policy
=> update release process to take account of major version

.github/workflows/ci.yml, CHANGELOG.md, Makefile, test/e2e/btc_rewards_distribution_e2e_test.go, test/e2e/btc_staking_e2e_test.go, test/e2e/btc_staking_pre_approval_e2e_test.go, test/e2e/configurer/chain/fp.go, test/e2e/configurer/chain/queries_btcstaking.go, test/e2e/configurer/chain/upgrade.go, test/e2e/configurer/config/constants.go, test/e2e/configurer/upgrade.go, test/e2e/e2e_test.go, test/e2e/govProps/resume-finality.json, test/e2e/gov_finality_resume.go, test/e2e/software_upgrade_e2e_v1_test.go, x/finality/abci.go, x/finality/keeper/gov.go, x/finality/keeper/gov_test.go, x/finality/keeper/tallying.go
- Add simple fix to index block prior to tally in handler 
- Add new e2e test to check resume finality governance proposal
=> fix: resume finality

.github/workflows/ci.yml, CHANGELOG.md, Makefile, test/e2e/btc_rewards_distribution_e2e_test.go, test/e2e/btc_staking_e2e_test.go, test/e2e/btc_staking_pre_approval_e2e_test.go, test/e2e/configurer/chain/fp.go, test/e2e/configurer/chain/queries_btcstaking.go, test/e2e/configurer/chain/upgrade.go, test/e2e/configurer/config/constants.go, test/e2e/configurer/upgrade.go, test/e2e/e2e_test.go, test/e2e/govProps/resume-finality.json, test/e2e/gov_finality_resume.go, test/e2e/software_upgrade_e2e_v1_test.go, testutil/datagen/btcstaking.go, x/finality/abci.go, x/finality/keeper/gov.go, x/finality/keeper/gov_test.go, x/finality/keeper/tallying.go
- Modified CI to run the e2e tests in parallel (was a conflict already)
#748
=> chore: backport #748

CHANGELOG.md
=> chore: cl release v1rc9 (#754)

x/btccheckpoint/README.md, x/btcstaking/README.md, x/epoching/README.md, x/finality/README.md, x/zoneconcierge/README.md
=> chore: Update README docs with updated proto definitions

CHANGELOG.md, crypto/ecdsa/ecdsa.go, crypto/ecdsa/ecdsa_test.go
- Remove `ecdsa.Verify` and stick to `ecdsa.RecoverPublicKey`
=> crypto: remove Verify for ECDSA

CHANGELOG.md
Add changelog change for Babylon v1.0.0 release
=> Babylon v1 changelog

docs/ibc-relayer.md
1. `refresh = true` should be in the `[mode.clients]` section
2. The `client_refresh_rate` value should be enclosed in quotes
=> (fix) ibc-relayer.md hermes example

app/signer/bls.go, app/signer/bls_test.go, app/signer/private.go, app/signer/util.go, cmd/babylond/cmd/cmd_test.go, cmd/babylond/cmd/create_bls_key.go, cmd/babylond/cmd/flags.go, cmd/babylond/cmd/init.go, cmd/babylond/cmd/migrate_bls_key.go, cmd/babylond/cmd/root.go, cmd/babylond/cmd/show_bls_key.go, crypto/eots/eots_test.go, test/e2e/containers/containers.go, testutil/datagen/init_val.go
Backport https://github.com/babylonlabs-io/babylon/pull/793
=> backport: BLS key will be overwritten when the password is not retrieved 

CHANGELOG.md
=> bupmp cl v101

docs/bls_key_password_management.md
Updates docs to reflect new changes.
=> chore: update bls key management docs

docs/bls_key_password_management.md
Document recommendation for backing up bls keys
=> chore: update bls key docs with backup recommendation

CHANGELOG.md
- small patch release fixin the tmp dir bug, and cleaning makefile a bit
=> v102 changelog

CHANGELOG.md, app/keepers/keepers.go, cmd/babylond/cmd/cmd_test.go
On main branch the hook is already properly set up, on the old backport PR #588 it missed to add the hook
=> fix: btc stk hook of btclightclient

CHANGELOG.md, x/finality/abci.go, x/finality/keeper/gov.go, x/finality/keeper/gov_test.go, x/finality/keeper/rewarding.go, x/finality/keeper/rewarding_test.go, x/finality/keeper/tallying.go, x/finality/keeper/tallying_bench_test.go, x/finality/keeper/tallying_test.go, x/finality/types/constants.go
backport pr 745 from main  -> euphrates
more info here
https://babylonlabsworkspace.slack.com/archives/C07EDCYR77D/p1746107768340939?thread_ts=1746084304.462239&cid=C07EDCYR77D
=> [backport] limit number of finalized and rewarded blocks (#745)

CHANGELOG.md, test/replay/driver.go, test/replay/finality_test.go, test/replay/scenario_builder.go, x/finality/keeper/gov.go, x/finality/keeper/gov_test.go, x/finality/keeper/power_dist_change.go
=> backport: v11x #860

app/include_upgrade_mainnet.go, app/include_upgrade_testnet.go, app/upgrades/v1_1/upgrades.go
=> add v1.1 upgrade data

app/include_upgrade_mainnet.go, app/include_upgrade_testnet.go, app/upgrades/v1_1/upgrades.go
=> [release/v1.1.x backport] add v1.1 upgrade data (#857)

CHANGELOG.md, client/query/client.go, client/query/epoching.go, test/replay/driver.go, test/replay/finality_test.go, test/replay/scenario_builder.go, x/finality/keeper/gov.go, x/finality/keeper/gov_test.go, x/finality/keeper/power_dist_change.go
=> backport: v2x fix inactive fp signing info (#860)

CHANGELOG.md, app/signer/bls.go, app/signer/bls_test.go, cmd/babylond/cmd/root.go, cmd/babylond/cmd/verify_val_bls_key.go
=> chore: backport #850 BLS improvement including permission and and verification

CHANGELOG.md, app/app.go, app/keepers/keepers.go, app/upgrades/v2/upgrades.go, go.mod, go.sum, test/e2e/ibc_transfer_e2e_test.go
Closes https://github.com/babylonlabs-io/pm/issues/350
=> imp: add PFM module

CHANGELOG.md, app/app.go, app/keepers/keepers.go, app/upgrades/v2/upgrades.go, go.mod, go.sum, test/e2e/ibc_transfer_e2e_test.go
Closes https://github.com/babylonlabs-io/pm/issues/350
=> Backport: imp: add PFM module (#876)

CHANGELOG.md, app/app.go, app/keepers/keepers.go, app/upgrades/v2/upgrades.go, app/upgrades/v2/upgrades_test.go, go.mod, go.sum, test/e2e/configurer/chain/queries.go, test/e2e/ibc_transfer_e2e_test.go, test/e2e/ica_e2e_test.go, test/e2e/initialization/config.go, x/btccheckpoint/keeper/genesis_test.go
Rate limiter
ADR: https://github.com/babylonlabs-io/pm/pull/371 RFC: https://github.com/babylonlabs-io/pm/pull/355
---------
=> [backport] chore: wire up rate-limiter (#902)

CHANGELOG.md, types/validate.go, x/checkpointing/types/errors.go, x/checkpointing/types/genesis.go, x/epoching/types/epoching.go, x/finality/types/power_table.go, x/finality/types/power_table_test.go, x/monitor/keeper/genesis.go, x/monitor/types/genesis.go, x/monitor/types/genesis_test.go
After testing the export and import genesis on a local chain, encountered these validations that should be updated
=> chore(gen): Update genesis initialization validations

.goreleaser.yml, CHANGELOG.md
=> chore(backport): v2x 931 goreleaser

.goreleaser.yml, CHANGELOG.md
=> chore(backport): v3x 931 goreleaser

.mergify.yml, CHANGELOG.md
This change has been made by @GAtom22 from the Mergify workflow automation editor.
=> ci(Mergify): configuration update

CHANGELOG.md, x/finality/keeper/msg_server.go, x/finality/keeper/msg_server_test.go, x/finality/types/errors.go, x/finality/types/msg.go, x/finality/types/msg_test.go
Closes https://github.com/babylonlabs-io/babylon/issues/961
=> imp: update ValidateBasic in x/finality msgs

CHANGELOG.md, x/incentive/types/genesis.go, x/incentive/types/genesis_test.go
- Add validation of size and decode of `RefundableMsgKey`
=> chore: add validation of msg hashes size and decode

CHANGELOG.md, x/epoching/types/genesis.go, x/epoching/types/genesis_test.go
References 19th issue from audit
=> chore: val sequential epoch

CHANGELOG.md, x/finality/types/finality.go, x/finality/types/finality_test.go
=> imp(finality): update Evidence ValidateBasic

CHANGELOG.md, x/incentive/types/rewards.go, x/incentive/types/rewards_test.go
=> chore: validate stats positive

CHANGELOG.md, testutil/datagen/raw_checkpoint.go, x/checkpointing/types/checkpoint.go, x/checkpointing/types/checkpoint_test.go, x/checkpointing/types/errors.go, x/checkpointing/types/genesis_test.go, x/checkpointing/types/types.go, x/checkpointing/types/types_test.go
=> chore(checkpointing): update validations

CHANGELOG.md, x/incentive/keeper/genesis.go, x/incentive/keeper/genesis_test.go
=> imp(incentive): validate `LastProcessedHeightEventRewardTracker` on `InitGenesis`

CHANGELOG.md
v2rc3 release https://github.com/babylonlabs-io/babylon/pull/1185
=> chore: add v2.0.0-rc.3 to cl

CHANGELOG.md, x/btcstaking/keeper/finality_providers.go, x/btcstaking/keeper/keeper_test.go, x/btcstaking/types/btc_staking_consumer_events.go, x/finality/keeper/evidence.go, x/finality/keeper/msg_server.go, x/finality/keeper/msg_server_test.go, x/finality/types/expected_keepers.go, x/finality/types/mocked_keepers.go, x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go, x/zoneconcierge/types/expected_keepers.go
- Fills slashing events with secret key of the slashed finality provider
- Add test check that correct fields are filled
=> fix secret key propagation when slashing

CHANGELOG.md, cmd/babylond/cmd/flags.go, cmd/babylond/cmd/genesis.go, cmd/babylond/cmd/testnet.go, x/btcstaking/types/genesis_test.go, x/btcstaking/types/params.go
- adjust `testnet` command to modify the `max-finality-providers` in script
=> add max params to external commands

CHANGELOG.md, app/ante/fee_checker.go, app/ante/fee_checker_test.go, app/keepers/keepers.go, go.mod, go.sum, test/e2e/ibc_transfer_e2e_test.go
- new cosmos-sdk version contains fix to `x/distribution` module (https://github.com/cosmos/cosmos-sdk/security/advisories/GHSA-p22h-3m2v-cmgh) which we originally fixed by introducing bank restrictions
- with the fix bank restrictions can be removed
=> fix: bump cosmos-sdk and remove send restrictions

CHANGELOG.md, x/zoneconcierge/abci.go, x/zoneconcierge/keeper/hooks.go, x/zoneconcierge/keeper/ibc_packet.go, x/zoneconcierge/keeper/ibc_packet_btc_headers.go, x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go, x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
Closes https://github.com/babylonlabs-io/babylon/issues/1278
=> fix(zoneconcierge): don't panic on IBC send packet calls

CHANGELOG.md
Release v3.0.0-rc.0 change log update
=> change log update

CHANGELOG.md, test/integration/validate_basic_app_test.go, testutil/helper/helper.go, x/btclightclient/keeper/msg_server.go, x/btclightclient/types/msgs.go, x/finality/keeper/msg_server.go, x/finality/keeper/msg_server_test.go
=> fix: remove duplicated ValidateBasic checks

CHANGELOG.md
Update changelog for v2.3.0 release
=> cl23 update

docs/bitcoin-stake-expansion.md, docs/bitcoin-stake-extension.md
stake expansion docs
---------
=> [backport] docs: stake extension (#1423)
